name = "short-it"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

[vars]
UNKEY_API_ID = "%UNKEY_API_ID%"
DEFAULT_EXPIRATION = 604800 # 7 days

[[routes]]
pattern = "%CUSTOM_DOMAIN%"
custom_domain = true

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "SHORT_IT"
id = "%CLOUDFLARE_KV_NAMESPACE_ID%"
