name = "short-it"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

[vars]
UNKEY_API_ID = "api_3ACFP2xp814sVUw7y2nQGQrQXgnQ"
DEFAULT_EXPIRATION = 604800 # 7 days

[[routes]]
pattern = "mine.st"
custom_domain = true

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "SHORT_IT"
id = "50bb7687fbf147169a06acf28c74e332"
