name: 'Deploy to cloudflare workers'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: oven-sh/setup-bun@v1
      - uses: actions/checkout@v4

      - name: Replace variables in wrangler.toml
        run: |
          sed -i "s/%UNKEY_API_ID%/$UNKEY_API_ID/g" wrangler.toml
          sed -i "s/%CUSTOM_DOMAIN%/$CUSTOM_DOMAIN/g" wrangler.toml
          sed -i "s/%CLOUDFLARE_KV_NAMESPACE_ID%/$CLOUDFLARE_KV_NAMESPACE_ID/g" wrangler.toml
        env:
          UNKEY_API_ID: ${{ vars.UNKEY_API_ID }}
          CUSTOM_DOMAIN: ${{ vars.CUSTOM_DOMAIN }}
          CLOUDFLARE_KV_NAMESPACE_ID: ${{ vars.CLOUDFLARE_KV_NAMESPACE_ID }}

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: bun
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
